# Generated by Django 4.2.1 on 2024-02-25 04:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_privilegio', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'privilegios',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_producto', models.CharField(max_length=150, null=True)),
                ('description', models.IntegerField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Tablas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tabla', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'tablas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('rol', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('fecha_actualizacion', models.DateField(default=datetime.date.today, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuarios_privilegios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_privilegio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.privilegios')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.usuarios')),
            ],
            options={
                'db_table': 'usuarios_privilegios',
            },
        ),
        migrations.CreateModel(
            name='Privilegios_tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_privilegio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.privilegios')),
                ('id_tabla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.tablas')),
            ],
            options={
                'db_table': 'privilegios_tabla',
            },
        ),
    ]
