# Generated by Django 4.2.1 on 2024-02-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_productos_precio_alter_productos_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_Privilegios_Tablas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_privilegio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.privilegios')),
                ('id_tabla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.tablas')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.usuarios')),
            ],
            options={
                'db_table': 'usuarios_privilegios_tablas',
            },
        ),
        migrations.RemoveField(
            model_name='usuarios_privilegios',
            name='id_privilegio',
        ),
        migrations.RemoveField(
            model_name='usuarios_privilegios',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Privilegios_tabla',
        ),
        migrations.DeleteModel(
            name='Usuarios_privilegios',
        ),
    ]
